/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MemberRouteImport } from './routes/member'
import { Route as DivineRouteImport } from './routes/divine'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserNameRouteImport } from './routes/user.$name'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const DivineRoute = DivineRouteImport.update({
  id: '/divine',
  path: '/divine',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserNameRoute = UserNameRouteImport.update({
  id: '/user/$name',
  path: '/user/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/chart': typeof ChartRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/divine': typeof DivineRoute
  '/member': typeof MemberRoute
  '/profile': typeof ProfileRoute
  '/reading': typeof ReadingRoute
  '/shop': typeof ShopRoute
  '/user/$name': typeof UserNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/chart': typeof ChartRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/divine': typeof DivineRoute
  '/member': typeof MemberRoute
  '/profile': typeof ProfileRoute
  '/reading': typeof ReadingRoute
  '/shop': typeof ShopRoute
  '/user/$name': typeof UserNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/chart': typeof ChartRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/divine': typeof DivineRoute
  '/member': typeof MemberRoute
  '/profile': typeof ProfileRoute
  '/reading': typeof ReadingRoute
  '/shop': typeof ShopRoute
  '/user/$name': typeof UserNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/chart'
    | '/chat'
    | '/community'
    | '/divine'
    | '/member'
    | '/profile'
    | '/reading'
    | '/shop'
    | '/user/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/chart'
    | '/chat'
    | '/community'
    | '/divine'
    | '/member'
    | '/profile'
    | '/reading'
    | '/shop'
    | '/user/$name'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/chart'
    | '/chat'
    | '/community'
    | '/divine'
    | '/member'
    | '/profile'
    | '/reading'
    | '/shop'
    | '/user/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  ChartRoute: typeof ChartRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  DivineRoute: typeof DivineRoute
  MemberRoute: typeof MemberRoute
  ProfileRoute: typeof ProfileRoute
  ReadingRoute: typeof ReadingRoute
  ShopRoute: typeof ShopRoute
  UserNameRoute: typeof UserNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divine': {
      id: '/divine'
      path: '/divine'
      fullPath: '/divine'
      preLoaderRoute: typeof DivineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$name': {
      id: '/user/$name'
      path: '/user/$name'
      fullPath: '/user/$name'
      preLoaderRoute: typeof UserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  ChartRoute: ChartRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  DivineRoute: DivineRoute,
  MemberRoute: MemberRoute,
  ProfileRoute: ProfileRoute,
  ReadingRoute: ReadingRoute,
  ShopRoute: ShopRoute,
  UserNameRoute: UserNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
